version: "3"

services:
  fpm:
    build: # Info to build the Docker image
      context: docker # Specify where the Dockerfile is located (e.g. in the root directory of the project)
      dockerfile: Dockerfile-php # Specify the name of the Dockerfile
    environment: # You can use this section to set environment variables. But you can also use the .env file.
      - DATABASE_URL=mysql://root:root@db:3306/jobeet # Connection string for the database.
      - PHP_IDE_CONFIG=serverName=Test
    volumes:
      - ./:/var/www/project/:rw # Location of the project for php-fpm. Note this should be the same for NGINX.
    networks:
      - symfony # Docker containers (services) that need to connect to each other should be on the same network.

  nginx:
    build:
      context: docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:rw
      - ./ini/:/usr/local/etc/php/:rw
    ports:
      - 8005:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    networks:
      - symfony

  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PHP_IDE_CONFIG=serverName=Test
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/db/:/docker-entrypoint-initdb.d/
    networks:
      - symfony


networks:
  symfony:

volumes:
  persistent:
  sf_cache:
