<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/02/17 16:50:09
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 10,
));
