<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/02/19 15:00:11
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 6,
  'app_max_jobs_on_category' => 10,
));
